version: '3'

services:
  mongo:
    image: mongo
    restart: unless-stopped
  telegram:
    restart: unless-stopped
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    depends_on:
      - mongo
